#ifndef SECRETS_H
#define SECRETS_H

// Konfiguracja Blynk
#define BLYNK_TEMPLATE_ID "TMPL4cVan17KG"
#define BLYNK_TEMPLATE_NAME "Flora"
#define BLYNK_AUTH_TOKEN "Aih2Ua6C8ixAkR5lE1kkLvxhNo8LWzGr"

#define FLORA_BACKEND_BASE_URL "http://192.168.0.68:8080"
#define FLORA_BACKEND_TOKEN "YWMxYzBhZjhkMDllZWY0ZTdlMjY1YjJmN2JiZWNmMTI2OWJmMThjMmRlNmFiOWMwNzI5YWIzZDU3MjFhODNiMQ.aHR0cHM6Ly9zdnIxNTQuc3VwbGEub3Jn"
#define FLORA_BACKEND_DEVICE_ID "flora-1"

#endif // SECRETS_H 